server:
  port: 8761                    # 指定该Eureka实例的端口
spring:
  profiles:
    active: dev


---
spring:
  profiles: dev
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker1                 #指定profile=docker1
server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server1    #指定当profile=docker1时，主机名是eureka-server1
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
            defaultZone: http://eureka-server2:8762/eureka/    #将自己注册到 eureka-server2这个eureka服务上
  server:
    enable-self-preservation: false

---
spring:
  profiles: docker2
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server2
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 30
  client:
    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
            defaultZone: http://eureka-server1:8761/eureka/
  server:
    enable-self-preservation: false