## YAML Template.
---
server:
    port: 7000
    
spring:
    application:
        name: zuul
        
        
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
zuul:
    routes:
        feign-service:
            path: /testzuul/**
            serviceId: testprovider
