## YAML Template.
---
server:
    port: 8777
    
    
spring:
    application:
        name: testprovider
        
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/