## YAML Template.
---
server:
    port: 9898


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      
      
spring: 
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver 
        url: jdbc:mysql://47.95.114.105:3306/oauth?useUnicode=true&characterEncoding=utf-8
        username: root 
        password: 123456
