## YAML Template.
---
server:
  port: 9998     
  

    
eureka:
  client:
    prefer-ip-address: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
spring:
    application:
        name: GIVEMETOKEN
    datasource: 
        driver-class-name: com.mysql.jdbc.Driver 
        url: jdbc:mysql://47.95.114.105:3306/oauth?useUnicode=true&characterEncoding=utf-8
        username: root 
        password: 123456
        
        
        
