spring:
  application:
    name: api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: userService
          uri: lb://USERSERIVCE
          predicates:
          - Path=/api/user/**
          filters:
          - StripPrefix=2
        - id: 163
          uri: https://www.sina.com.cn/
          predicates:
          - Path=/api/sina/**
          filters:
          - StripPrefix=2
        - id: givemetoken
          uri: lb://GIVEMETOKEN
          predicates:
          - Path=/plzseparate
        - id: testzuul
          uri: lb://TESTPROVIDER
          predicates:
          - Path=/hellozuul


server:
  port: 8084
#zuul:
#  routes:
#    userService:                    #自定义的转发规则
#      path: /api/user/**
#      service-id: userSerivce                    #可以是一个注册的服务名
#    #  url:                           #可以是一个物理的url
#    orderService:
#      path: /api/order/**
#      service-id: orderSerivce
#    baidu:
#      path: /api/a/**
#      url: http://www.baidu.com

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:8761/eureka/,http://eureka-server2:8762/eureka/
  instance:
    prefer-ip-address: true